name: Minimal Android CI Workflow

on:
  push:
    branches:
      - feature/47
jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run Tests
        run: bash ./gradlew test --stacktrace
      - name: Decode
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'android_keystore.jks'
          fileDir: '/home/runner/work/<<project name>>/<<project name>>/app/keystore/'
          encodedString: ${{ secrets.KEYSTORE }}
      - name: Build signed APK
        run: ./gradlew assembleRelease -x test
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: Upload APK
        uses: actions/upload-artifact@v3.1.2
        with:
          name: <<application name>>
          path: app/build/outputs/apk/release/<<application name>>_${{ github.event.inputs.version }}.apk